const mongoose = require("mongoose");
const Language = require("../models/languages");

connect();

async function connect() {
  await mongoose.connect("mongodb://localhost:27017/movie_library");

  try {
    const languages = await Language.find({}); // see all the Languages
    if (languages.length > 0) {
      console.log("languages table is not empty. not loading languages");
    } else {
      const result = await Language.insertMany([
        { _id: "he", name: "Hebrew" },
        { _id: "en", name: "English" },
        { _id: "ru", name: "Russian" },
        { _id: "ar", name: "Arabic" },
        { _id: "es", name: "Spanish" },
        { _id: "ab", name: "Abkhazian" },
        { _id: "aa", name: "Afar" },
        { _id: "af", name: "Afrikaans" },
        { _id: "ak", name: "Akan" },
        { _id: "sq", name: "Albanian" },
        { _id: "am", name: "Amharic" },
        { _id: "an", name: "Aragonese" },
        { _id: "hy", name: "Armenian" },
        { _id: "as", name: "Assamese" },
        { _id: "av", name: "Avaric" },
        { _id: "ae", name: "Avestan" },
        { _id: "ay", name: "Aymara" },
        { _id: "az", name: "Azerbaijani" },
        { _id: "bm", name: "Bambara" },
        { _id: "ba", name: "Bashkir" },
        { _id: "eu", name: "Basque" },
        { _id: "be", name: "Belarusian" },
        { _id: "bn", name: "Bengali" },
        { _id: "bi", name: "Bislama" },
        { _id: "bs", name: "Bosnian" },
        { _id: "br", name: "Breton" },
        { _id: "bg", name: "Bulgarian" },
        { _id: "my", name: "Burmese" },
        { _id: "ca", name: "Catalan, Valencian" },
        { _id: "km", name: "Central Khmer" },
        { _id: "ch", name: "Chamorro" },
        { _id: "ce", name: "Chechen" },
        { _id: "ny", name: "Chichewa, Chewa, Nyanja" },
        { _id: "zh", name: "Chinese" },
        {
          _id: "cu",
          name: "Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic",
        },
        { _id: "cv", name: "Chuvash" },
        { _id: "kw", name: "Cornish" },
        { _id: "co", name: "Corsican" },
        { _id: "cr", name: "Cree" },
        { _id: "hr", name: "Croatian" },
        { _id: "cs", name: "Czech" },
        { _id: "da", name: "Danish" },
        { _id: "dv", name: "Divehi, Dhivehi, Maldivian" },
        { _id: "nl", name: "Dutch, Flemish" },
        { _id: "dz", name: "Dzongkha" },
        { _id: "eo", name: "Esperanto" },
        { _id: "et", name: "Estonian" },
        { _id: "ee", name: "Ewe" },
        { _id: "fo", name: "Faroese" },
        { _id: "fj", name: "Fijian" },
        { _id: "fi", name: "Finnish" },
        { _id: "fr", name: "French" },
        { _id: "ff", name: "Fulah" },
        { _id: "gd", name: "Gaelic, Scottish Gaelic" },
        { _id: "gl", name: "Galician" },
        { _id: "lg", name: "Ganda" },
        { _id: "ka", name: "Georgian" },
        { _id: "de", name: "German" },
        { _id: "el", name: "Greek, Modern" },
        { _id: "gn", name: "Guarani" },
        { _id: "gu", name: "Gujarati" },
        { _id: "ht", name: "Haitian" },
        { _id: "ha", name: "Hausa" },
        { _id: "hz", name: "Herero" },
        { _id: "hi", name: "Hindi" },
        { _id: "ho", name: "Hiri Motu" },
        { _id: "hu", name: "Hungarian" },
        { _id: "is", name: "Icelandic" },
        { _id: "io", name: "Ido" },
        { _id: "ig", name: "Igbo" },
        { _id: "id", name: "Indonesian" },
        {
          _id: "ia",
          name: "Interlingua (International Auxiliary Language Association)",
        },
        { _id: "ie", name: "Interlingue, Occidental" },
        { _id: "iu", name: "Inuktitut" },
        { _id: "ik", name: "Inupiaq" },
        { _id: "ga", name: "Irish" },
        { _id: "it", name: "Italian" },
        { _id: "ja", name: "Japanese" },
        { _id: "jv", name: "Javanese" },
        { _id: "kl", name: "Kalaallisut, Greenlandic" },
        { _id: "kn", name: "Kannada" },
        { _id: "kr", name: "Kanuri" },
        { _id: "ks", name: "Kashmiri" },
        { _id: "kk", name: "Kazakh" },
        { _id: "ki", name: "Kikuyu, Gikuyu" },
        { _id: "rw", name: "Kinyarwanda" },
        { _id: "ky", name: "Kirghiz, Kyrgyz" },
        { _id: "kv", name: "Komi" },
        { _id: "kg", name: "Kongo" },
        { _id: "ko", name: "Korean" },
        { _id: "kj", name: "Kuanyama, Kwanyama" },
        { _id: "ku", name: "Kurdish" },
        { _id: "lo", name: "Lao" },
        { _id: "la", name: "Latin" },
        { _id: "lv", name: "Latvian" },
        { _id: "li", name: "Limburgan, Limburger, Limburgish" },
        { _id: "ln", name: "Lingala" },
        { _id: "lt", name: "Lithuanian" },
        { _id: "lu", name: "Luba-Katanga" },
        { _id: "lb", name: "Luxembourgish, Letzeburgesch" },
        { _id: "mk", name: "Macedonian" },
        { _id: "mg", name: "Malagasy" },
        { _id: "ms", name: "Malay" },
        { _id: "ml", name: "Malayalam" },
        { _id: "mt", name: "Maltese" },
        { _id: "gv", name: "Manx" },
        { _id: "mi", name: "Maori" },
        { _id: "mr", name: "Marathi" },
        { _id: "mh", name: "Marshallese" },
        { _id: "mn", name: "Mongolian" },
        { _id: "na", name: "Nauru" },
        { _id: "nv", name: "Navajo, Navaho" },
        { _id: "ng", name: "Ndonga" },
        { _id: "ne", name: "Nepali" },
        { _id: "nd", name: "North Ndebele" },
        { _id: "se", name: "Northern Sami" },
        { _id: "no", name: "Norwegian" },
        { _id: "nb", name: "Norwegian Bokmål" },
        { _id: "nn", name: "Norwegian Nynorsk" },
        { _id: "oc", name: "Occitan" },
        { _id: "oj", name: "Ojibwa" },
        { _id: "or", name: "Oriya" },
        { _id: "om", name: "Oromo" },
        { _id: "os", name: "Ossetian, Ossetic" },
        { _id: "pi", name: "Pali" },
        { _id: "ps", name: "Pashto, Pushto" },
        { _id: "fa", name: "Persian" },
        { _id: "pl", name: "Polish" },
        { _id: "pt", name: "Portuguese" },
        { _id: "pa", name: "Punjabi, Panjabi" },
        { _id: "qu", name: "Quechua" },
        { _id: "ro", name: "Romanian, Moldavian, Moldovan" },
        { _id: "rm", name: "Romansh" },
        { _id: "rn", name: "Rundi" },
        { _id: "sm", name: "Samoan" },
        { _id: "sg", name: "Sango" },
        { _id: "sa", name: "Sanskrit" },
        { _id: "sc", name: "Sardinian" },
        { _id: "sr", name: "Serbian" },
        { _id: "sn", name: "Shona" },
        { _id: "ii", name: "Sichuan Yi, Nuosu" },
        { _id: "sd", name: "Sindhi" },
        { _id: "si", name: "Sinhala, Sinhalese" },
        { _id: "sk", name: "Slovak" },
        { _id: "sl", name: "Slovenian" },
        { _id: "so", name: "Somali" },
        { _id: "nr", name: "South Ndebele" },
        { _id: "st", name: "Southern Sotho" },
        { _id: "su", name: "Sundanese" },
        { _id: "sw", name: "Swahili" },
        { _id: "ss", name: "Swati" },
        { _id: "sv", name: "Swedish" },
        { _id: "tl", name: "Tagalog" },
        { _id: "ty", name: "Tahitian" },
        { _id: "tg", name: "Tajik" },
        { _id: "ta", name: "Tamil" },
        { _id: "tt", name: "Tatar" },
        { _id: "te", name: "Telugu" },
        { _id: "th", name: "Thai" },
        { _id: "bo", name: "Tibetan" },
        { _id: "ti", name: "Tigrinya" },
        { _id: "to", name: "Tonga (Tonga Islands)" },
        { _id: "ts", name: "Tsonga" },
        { _id: "tn", name: "Tswana" },
        { _id: "tr", name: "Turkish" },
        { _id: "tk", name: "Turkmen" },
        { _id: "tw", name: "Twi" },
        { _id: "ug", name: "Uighur, Uyghur" },
        { _id: "uk", name: "Ukrainian" },
        { _id: "ur", name: "Urdu" },
        { _id: "uz", name: "Uzbek" },
        { _id: "ve", name: "Venda" },
        { _id: "vi", name: "Vietnamese" },
        { _id: "vo", name: "Volapük" },
        { _id: "wa", name: "Walloon" },
        { _id: "cy", name: "Welsh" },
        { _id: "fy", name: "Western Frisian" },
        { _id: "wo", name: "Wolof" },
        { _id: "xh", name: "Xhosa" },
        { _id: "yi", name: "Yiddish" },
        { _id: "yo", name: "Yoruba" },
        { _id: "za", name: "Zhuang, Chuang" },
        { _id: "zu", name: "Zulu" },
      ]);
    }
  } catch (err) {
    console.log("Problem creating Languages table: \n " + err);
  }
}
